packages:
  - "packages/*"
  - "fixtures/*"
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: true
  unrs-resolver: set this to true or false
