import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import * as Accordion from "@radix-ui/react-accordion";
import * as Dialog from "@radix-ui/react-dialog";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={100}
            height={20}
            priority
          />
          <div className={styles.intro}>
            <h1>
              To get started, edit the{" "}
              <code className={styles.code}>index.js</code> file.
            </h1>
            <p>
              Looking for a starting point or more instructions? Head over to{" "}
              <a
                href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Templates
              </a>{" "}
              or the{" "}
              <a
                href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Learning
              </a>{" "}
              center.
            </p>
          </div>
          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={16}
                height={14}
              />
              Deploy Now
            </a>
            <a
              className={styles.secondary}
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Documentation
            </a>
          </div>

          <div id="vendor-components">
            <h2>Radix Accordion &amp; Dialog examples</h2>
            <p>
              Rendered by real npm dependencies (
              <code>@radix-ui/react-accordion</code>,{" "}
              <code>@radix-ui/react-dialog</code>), not application code —
              used to verify click-to-source resolves here, not into the
              library&apos;s own internals.
            </p>
            <Accordion.Root type="single" collapsible>
              <Accordion.Item value="item-1">
                <Accordion.Header>
                  <Accordion.Trigger id="vendor-accordion-trigger">
                    Vendor accordion trigger
                  </Accordion.Trigger>
                </Accordion.Header>
                <Accordion.Content id="vendor-accordion-content">
                  Vendor accordion content
                </Accordion.Content>
              </Accordion.Item>
            </Accordion.Root>
            <Dialog.Root>
              <Dialog.Trigger id="vendor-dialog-trigger">
                Open vendor dialog
              </Dialog.Trigger>
              <Dialog.Portal>
                <Dialog.Overlay />
                <Dialog.Content id="vendor-dialog-content">
                  <Dialog.Title>Vendor dialog</Dialog.Title>
                  <Dialog.Description>
                    Rendered by @radix-ui/react-dialog, portaled to
                    document.body.
                  </Dialog.Description>
                  <Dialog.Close id="vendor-dialog-close">Close</Dialog.Close>
                </Dialog.Content>
              </Dialog.Portal>
            </Dialog.Root>
          </div>
        </main>
      </div>
    </>
  );
}
